---

name: BATS

# yamllint disable-line rule:truthy
on: [push, pull_request, workflow_dispatch]

jobs:
  testjob:
    runs-on: ubuntu-22.04

    steps:
      - name: apt-get update
        run: sudo apt-get update

      - name: apt-get install
        run: sudo apt-get -y install bats

      - uses: actions/checkout@v2
        with:
          fetch-path: 0  # some tests need release tags
          path: sof-bin

      # For sof/tools/sof_ri_info.py
      - uses: actions/checkout@v2
        with:
          repository: thesofproject/sof
          path: sof

      - name: run tests
        run: cd sof-bin && git fetch --tags && bats -j 4 tests/*.bats
